color:
  brandColors:
    - '#FFFFFF'
    - '#897249'
    - '#E1DDC0'
    - '#C4B37B'
    - '#54401D'
  brandStrength: 0.512336
  lightness: 0.281614
  rhythmicContrast: 0.693257
  saturation: 0.745888
layout_spectrum: 0.390625
name: DAVAO HOMES
typography_spectrum: 0.444901
