color:
  brandColors:
    - '#FFFFFF'
    - '#4E2708'
    - '#B1C2CC'
    - '#705B48'
    - '#C76F25'
  brandStrength: 0.512336
  lightness: 0.281614
  rhythmicContrast: 0.693257
  saturation: 0.745888
layout_spectrum: 0.390625
name: DAVAO HOMES
typography_spectrum: 0.444901
